default-schema: rectangles
algorithm:
  size: 10
  power: 1.5
  upper-bound: 20

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/rectangle-problem-db
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${spring.datasource.url}
      password: postgres
      username: postgres
      maximum-pool-size: 40

  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: ${default-schema}
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        jdbc:
          batch_size: 1000
          order_inserts: true
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create