default-schema: rectangle_problem_min
algorithm:
  size: ${RECTANGLE_SIZE}
  power: 1.5
  upper-bound: ${UPPER_BOUND}
  paulhus-upper-bound: ${PAULHUS_UPPER_BOUND}
server:
  shutdown: graceful
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/rectangle-problem-db
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: ${spring.datasource.url}
      password: postgres
      username: postgres
      maximum-pool-size: 40

  jpa:
    show-sql: false
    properties:
      hibernate:
        default_schema: ${default-schema}
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        jdbc:
          batch_size: 1000
          order_inserts: true
        hbm2dll:
          create_namespaces: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    open-in-view: false